### ISSUE TITLE
Query มาตรา

### ISSUE THREAD

**Issue by GravitySow** [kaogeek/cons60-web#12]
หมวดทั้งหมด
ผู้อภิปราย
 - ทั้งหมด
 - แบ่งตามหมวด
มาตรา
 - ทั้งหมด
 - แบ่งตามหมวด

**Comment by PutawanDE** [comment]
อันนี้คือ query ไรหรอครับ พอดีว่าผมเขียน query หาจำนวนครั้งในการแก้ไขรายมาตรา รายหมวด และก็ใครแก้ไขอะไรกี่ครั้งแล้วนะครับ เป็น query ที่ใช้ในหน้า overview ทั้ง 3 แบบ: ดูตามหมวด, ผู้อภิปราย, มาตรา เชื่อมกันแล้วเรียบร้อยครับ

**Comment by iampz** [comment]
สำหรับหมวด, มาตรา และช่องอื่น ใช้คำสั่ง .list(columnName)
ส่วนผู้อภิปราย ใช้คำสั่ง .listPanelists()

ลองเล่นในหน้านี้ได้ หรือถ้าสงสัยสอบถามไว้นะ
https://iampz.github.io/c60-data-query/

@PutawanDE เข้าใจว่าใช้งานได้ ไม่ติดปัญหาอะไรเนอะ
ยังไงผมปิด issue นี้ไปก่อนละกันครับ
