### ISSUE TITLE
หน้า search

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#16]
- หน้าที่แสดงเมื่อกด search bar

![image](https://github.com/kaogeek/cons60-web/assets/31311349/d2faaf73-918a-4beb-a778-ee9a26a3e250)

**Comment by GravitySow** [comment]
เหลือเทส

**Comment by GravitySow** [comment]
เพิ่มคำว่ามาตราหน้าเลขมาตรา
