### ISSUE TITLE
ใส่เนื้อหาหน้า about

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#22]
- รวมถึง PDF

**Comment by PutawanDE** [comment]
- แก้ content
- ใส่ reference
- รายชื่ออาสาสมัคร

**Comment by GravitySow** [comment]
Note: รอรูปอาสาสมัคร

**Comment by iampz** [comment]
ส่วนแก้รูปอาสาจะอยู่ใน issue #36
ดังนั้น issue นี้จึงปิดได้เลย
