### ISSUE TITLE
Set custom domain name, Server, Deployment

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#25]

**Comment by iampz** [comment]
แตกส่วน Github Pages - Custom Doamin ไปที่ #46

**Comment by iampz** [comment]
issue นี้เดี๋ยวจะคุยกับทางสภาวันพรุ่งนี้ครับ

**Comment by iampz** [comment]
domain, server ทางสภาจัดการให้แล้ว
ตอนนี้จะเหลือ setup server, deployment ครับ

**Comment by iampz** [comment]
เหลือแค่ https ที่ทำเองไม่ได้ (ไม่มี cert) ตรงนี้ได้แจ้งให้ทางทีมสภาทำต่อไว้แล้ว
http://cons60-library.parliament.go.th/
