### ISSUE TITLE
แบบฟอร์มการประเมินความพึงพอใจการใช้เว็บไซต์

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#27]
footer ด้านล่าง

**Comment by iampz** [comment]
ลองใส่เป็น mockup ให้เค้าเห็นก่อน

**Comment by iampz** [comment]
ลิ้งค์หน้าประเมินความพึงพอใจ
https://form.parliament.go.th/questionnaire/SurveyUser/SurveyUserTakeNoLogin.php?survey_id=370881
