### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#29]
เน้นเรื่อง testing ก่อน
ทั้ง desktop, mobile

**Comment by GravitySow** [comment]
จำนวนครั้งอยู่คนละบรรทัดกัน ถ้าชื่อสั้นกับยาว

![image](https://github.com/kaogeek/cons60-web/assets/72992384/e142c73b-1fc5-4400-b95c-e22a1ee429af)
![image](https://github.com/kaogeek/cons60-web/assets/72992384/6d9a6220-dc9d-4d57-8362-8f0201dbfce6)

**Comment by iampz** [comment]
ช่อง search ล้นจอ

![Screenshot_2024-03-12-01-42-26-63_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/kaogeek/cons60-web/assets/523813/0a07acfc-cd29-43c2-92c5-6227b8f77314)
