### ISSUE TITLE
แก้โลโก้และ theme สีที่ใช้ในเว็บให้เป็นไปตามเว็บรัฐสภา

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#32]
แดงมารูน เทา

https://www.parliament.go.th/

**Comment by iampz** [comment]
parliament palette
![parliament-palette](https://github.com/kaogeek/cons60-web/assets/523813/b43ce300-f97e-4d8a-8391-8f25d2fbb6f5)

**Comment by iampz** [comment]
commit ล่าสุดลองทำตีมสีใหม่กับหน้าแรกและหน้า chapter
น่าจะต้องเปลี่ยน background หน้าแรกให้เกรดสีไปทางน้ำตาลแดงตามสีพื้นหลังใหม่

ฝากภู @PutawanDE เอาขึ้น github pages ไว้หน่อยนะ จะเอาให้พี่ปิ๋มดูก่อนว่าโอเคมั้ย
ถ้าเค้าโอเคจะได้แก้ทั้งเว็บแล้วค่อยปิด issue

**Comment by iampz** [comment]
แก้เรื่องเกรดสี background image แล้ว และแก้ส่วนอื่นให้ครบถ้วนเฉพาะสองหน้าที่จะให้พี่ปิ๋มดูแล้ว รอเอาขึ้น main / github pages
