### ISSUE TITLE
แก้ layout หน้า about สำหรับ mobile และใส่รูปผู้จัดทำ

### ISSUE THREAD

**Issue by PutawanDE** [kaogeek/cons60-web#36]
- ในหน้า about

**Comment by iampz** [comment]
แจ้งพี่ปิ๋มไปอีกรอบแล้ว น่าจะส่งรูปให้พรุ่งนี้

**Comment by iampz** [comment]
issue นี้จะแก้รวมกับ
1. แก้ layout หน้าแรกบน mobile
2. แก้สีของ nav บน mobile
