### ISSUE TITLE
Fix page title and description

### ISSUE THREAD

**Issue by GravitySow** [kaogeek/cons60-web#41]
![image](https://github.com/kaogeek/cons60-web/assets/72992384/1f1dfa9b-1089-4df3-8d1e-52f50846579d)

**Comment by GravitySow** [comment]
บันทึกกรธ. - รัฐสภาไทย

**Comment by iampz** [comment]
issue นี้รอแป๊บนะ แอมคุยกับพี่ปิ๋มไปอยู่ เดาว่าเค้าน่าจะแจ้งกลับมาอีกทีพรุ่งนี้ หรือมีนคุยกับทางพี่ปิ๋มตรงเลยก็ได้

**Comment by iampz** [comment]
มีแก้ design หลายส่วน อธิบายลำบาก ตรงนี้เดี๋ยวแอมทำเองเลยละกัน
