### ISSUE TITLE
แก้ไขหน้า "ข้อมูลที่เกี่ยวข้อง"

### ISSUE THREAD

**Issue by GravitySow** [kaogeek/cons60-web#68]
<img width="1439" alt="Screenshot 2024-03-12 at 14 18 44" src="https://github.com/kaogeek/cons60-web/assets/72992384/2fbad056-0aad-4014-988f-99b2281a7326">

 - แก้สี font 
 - ลบ underline แล้วเวลา cursor ให้มี underline สีขาวขึ้น

**Comment by iampz** [comment]
เดี๋ยวแอมแก้ design เพิ่มละกันเนอะ
